# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os:  [ubuntu-latest]
        # pip cache paths
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      run : |
          sudo apt-get update
          sudo apt-get install -y \
              libboost-python-dev \
              build-essential \
              python3-dev
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # use pip caching
    - uses: actions/cache@v4
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    # Actually build it
    - name: Build
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install libboost-python-dev
        pip install .
        python3 -m pytest ./tests/test_interface.py
